version: '3.8'

x-collector-mongo: &collector-mongo-env
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: toor
  MONGO_HOST: mongo
  MONGO_DBNAME: reproductions
  MONGO_PORT: 27017

x-xx-port-mapping:
  collector: &collector-ports
    - 8080:8080
  collecor-mongo: &collector-mongo-ports
    - 27017:27017

x-xx-common-services-settings: &common-settings
  restart: always

services:
  collector:
    <<: *common-settings
    build:
      context: ./
      dockerfile: dev.Dockerfile
      args:
        MODULE_NAME: metrics-collector
        MODULE_PATH: metrics-collector
    volumes:
      - ./:/go/src/metrics-collector
    command: bee run -downdoc=true -gendoc=true
    environment: *collector-mongo-env
    ports: *collector-ports

  mongo:
    <<: *common-settings
    image: mongo
    environment: *collector-mongo-env
    ports: *collector-mongo-ports
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
